CREATE TABLE review (
    id BIGINT PRIMARY KEY,
    content VARCHAR(255) NOT NULL,
    rating DOUBLE,
    booking_id BIGINT NOT UNIQUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE passenger (
    id BIGINT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE driver (
    id BIGINT PRIMARY KEY,
    name VARCHAR(255),
    license_number VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE booking (
    id BIGINT PRIMARY KEY,
    booking_type ENUM('SCHEDULED', 'CANCELLED', 'CAB_ARRIVED', 'ASSIGNING_DRIVER', 'IN_RIDE', 'COMPLETED'),
    total_distance BIGINT,
    start_time TIMESTAMP,
    end_time TIMESTAMP,
    driver_id BIGINT,
    passenger_id BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE passenger_review (
    id BIGINT PRIMARY KEY,
    passenger_review_content VARCHAR(255) NOT NULL,
    passenger_rating VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

ALTER TABLE review ADD CONSTRAINT fk_review_booking FOREIGN KEY (booking_id) REFERENCES booking(id);
ALTER TABLE booking ADD CONSTRAINT fk_booking_driver FOREIGN KEY (driver_id) REFERENCES driver(id);
ALTER TABLE booking ADD CONSTRAINT fk_booking_passenger FOREIGN KEY (passenger_id) REFERENCES passenger(id);

ALTER TABLE passenger_review ADD CONSTRAINT fk_passenger_review FOREIGN KEY (id) REFERENCES review(id);
